### ISSUE TITLE
Disallow whitespace before an entry

### ISSUE THREAD

**Issue by spagy** [l20n/spec#4]
From grammar.ebnf:

```
body ::= (__ entry NL)* (__ entry)? EOF;
```

Before every occurrence of there is optional whitespace. However when playing around with tinker whitespace isn't allowed before any of the three types of entry (comment, message, section).

Each time the error message is "Expected new line and a new entry"

**Comment by stasm** [comment]
Yup, good catch. Do you want to create a PR for this?

**Comment by spagy** [comment]
There it is :)
