### ISSUE TITLE
Bultins should be specified

### ISSUE THREAD

**Issue by spagy** [l20n/spec#6]
This is actually more of a question.

```
builtin ::= [A-Z_.?-]+;
```

A builtin according to the above definition doesn't have to be one of the builtins that are built-in to l20n. To me it would make sense for only available builtins to be legal. Is there a reason it shouldn't be that way?

**Comment by stasm** [comment]
The grammar specifiec the rules of what can be a builtin.  Different implementations (or versions of the same implementation) might provide different builtins.  The parser should only understand that something looks like a builtin.

I'm going to close this issue but let me know if you have additional questions about this.

**Comment by spagy** [comment]
I think it would be nice for bultins to be part of the spec rather than implementation specific so their behaviour is universally defined and they can be used without worrying about portability.

I can understand the reason for not wanting to include specific builtins in the grammar though so I won't kick up a fuss.

**Comment by GlenDC** [comment]
I do think it would be great if those builtins at least are listed, so that different implementations have at least an aim and clear idea of what builtins a typical L20n (FTL) user might expect. Sorry to talk into a closed issue.
